# Generated by cucumber-sinatra. (2015-12-02 11:35:04 +0900)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = WorkshopApp

class WorkshopAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers

  def log_in_admin
    WorkshopApp.admin_logged_in = true
  end
end

World do
  WorkshopAppWorld.new
end
